### ISSUE TITLE
Polymorphic functions are not polymorphic enough

### ISSUE THREAD

**Issue by mbenke** [argotorg/solcore#66]
In the example

```
forall any.function undefined() -> any {
  assembly {
    revert(0,0)
  };
}

function useWord(w:word) {}

contract Magic {
function main() {
  useWord(undefined());
}
}
```

`undefined` typechcks, but cannot be used polymorphically:

```
Types: () and word do not unify
 - in:useWord(undefined())
 - in:function main () {
   useWord(undefined());
}
```

**Comment by mbenke** [comment]
Possibly related: in the following code

```
// removing this function breaks things too; WHY?
forall any.function undefined() -> any {
  assembly {
    revert(0,0)
  };
}

class  ref : Ref(deref) {
  function load (r:ref) -> deref;
  function store(r:ref, v:deref) -> unit;
}

instance stack(a) : Ref(a) {
}

instance stack(a) : Ref(a) {}
data MemberAccess(ty, field) = MemberAccess(ty);

data PairFst = PairFst;
data PairSnd = PairSnd;

pragma no-bounded-variable-condition Ref;
data XRef(st, field, fieldType) = XRef(st, field);
instance (r:Ref( (a,b) ) )=>  XRef(r, PairFst, a) : Ref(a) {}
instance (r:Ref( (a,b) ) )=>  XRef(r, PairSnd, b) : Ref(b) {}

contract AssignNested {
  function main() {
    let x : stack( (word, (word, word)) );
    let z : stack( (word, (word, word)) );

    // either of the next lines is fine on their own, but not together
    //Ref.store( XRef(z,PairFst), 21); 
    Ref.store( XRef(XRef(x, PairSnd), PairFst), 20 );

   return 77;

  }
}
```

either of the stores to x and z works on their own but not together. Even strangr, removing the unused function `undefined` also seems to break things

**Comment by rodrigogribeiro** [comment]
Fixed on branch `polymorphic-undefined`.

**Comment by mbenke** [comment]
#68 solves the original problem (`undefined`). While it doesn't solve the second problem (references), I have created a separate issue (#72) for it so that #68 can be merged and this issue closed.

**Comment by rodrigogribeiro** [comment]
Fixed on `main`.
